potato/urls.py
from django.contrib.auth.views import LoginView, logout_then_login
from django.urls import path

from potato.views import categories, issues, main, scorecoefficients, significancelevels, users

urlpatterns = [
    # main
    path("", main.index, name="index"),
    # auth
    path("login", LoginView.as_view(), name="login"),
    path("logout", logout_then_login, name="logout"),
    # users
    path("admin/users", users.index, name="admin-users"),
    path("admin/users/create", users.create, name="admin-users-create"),
    path("admin/users/<int:user_id>/edit", users.edit, name="admin-users-edit"),
    path("admin/users/<int:user_id>/delete", users.delete, name="admin-users-delete"),
    path("admin/users/<int:user_id>/check", users.check, name="admin-users-check"),
    # categories
    path("admin/categories", categories.index, name="admin-categories"),
    path("admin/categories/create", categories.create, name="admin-categories-create"),
    path("admin/categories/<int:category_id>/edit", categories.edit, name="admin-categories-edit"),
    path("admin/categories/<int:category_id>/delete", categories.delete, name="admin-categories-delete"),
    path("admin/categories/<int:category_id>/check", categories.check, name="admin-categories-check"),
    # significance levels
    path("admin/significance", significancelevels.index, name="admin-significance"),
    path("admin/significance/create", significancelevels.create, name="admin-significance-create"),
    path("admin/significance/<int:significance_id>/edit", significancelevels.edit, name="admin-significance-edit"),
    path("admin/significance/<int:significance_id>/delete", significancelevels.delete, name="admin-significance-delete"),
    path("admin/significance/<int:significance_id>/check", significancelevels.check, name="admin-significance-check"),
    # score coefficients
    path("admin/scoring", scorecoefficients.index, name="admin-scoring"),
    path("admin/scoring/edit", scorecoefficients.edit, name="admin-scoring-edit"),
    # issues
    path("issues/open", issues.index, {'closed': False}, name="issues-open"),
    path("issues/closed", issues.index, {'closed': True}, name="issues-closed"),
    path("issues/create", issues.create, name="issues-create"),
    path("issues/<int:issue_id>", issues.edit, name="issues-edit"),
    path("issues/<int:issue_id>/delete", issues.delete, name="issues-delete"),
    path("issues/<int:issue_id>/comment", issues.comment, name="issues-comment"),
    path("issues/<int:issue_id>/comment/<int:comment_id>", issues.edit_comment, name="issues-comment-edit"),
]

tgoas/urls.py
from django.urls import include, path
from django.conf import settings

urlpatterns = [path("", include("potato.urls"))]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

potato/models/issue.py
from datetime import date

from django.conf import settings
from django.core.mail import send_mail
from django.db import models
from django.db.models.signals import pre_save, post_init, post_save
from django.dispatch import receiver
from django.template.defaultfilters import date as dateformat
from django.template.loader import render_to_string
from django.utils import timezone
from django.utils.functional import cached_property

from potato.phase import Phase

from .category import Category
from .scorecoefficient import ScoreCoefficient
from .significancelevel import SignificanceLevel
from .user import User


class Issue(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT, related_name="issues")
    title = models.CharField(max_length=50)
    assigned_to = models.ForeignKey(User, on_delete=models.PROTECT, related_name="assigned_issues")
    significance = models.ForeignKey(
        SignificanceLevel, on_delete=models.PROTECT, related_name="issues"
    )
    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name="issues")
    _phase = models.ForeignKey(
        ScoreCoefficient,
        on_delete=models.PROTECT,
        related_name="+",
        choices=Phase.choices(),
    )
    due_date = models.DateField()
    description = models.TextField(null=True, blank=True)
    draft_notes = models.TextField(null=True, blank=True)
    screening_notes = models.TextField(null=True, blank=True)
    analysis_notes = models.TextField(null=True, blank=True)
    implementation_notes = models.TextField(null=True, blank=True)
    verification_notes = models.TextField(null=True, blank=True)

    @cached_property
    def activity(self):
        """
        All of this issue's associated HistoryItems and Comments, sorted in a
        list by their creation time
        """

        items = [i for i in self.comments.all()] + [i for i in self.history.all()]
        return sorted(items, key=lambda i: i.created_at, reverse=True)

    def can_edit(self, request):
        """
        Flag representing whether the current user has permission to edit this
        issue
        """

        return self.assigned_to == request.user or request.user.is_staff

    @property
    def next_phase(self):
        """
        Display name of the phase that comes after the current phase
        """

        return Phase(self.phase + 1).name.capitalize() if self.phase < Phase.CLOSED else None

    @property
    def phase(self):
        """
        Property getter for integer value of the current phase.
        """

        return self._phase_id

    @phase.setter
    def phase(self, value):
        """
        Property setter for integer value of the current phase.
        """

        setattr(self, "_phase_id", value)

    @property
    def prev_phase(self):
        """
        Display name of the phase that comes before the current phase
        """

        return Phase(self.phase - 1).name.capitalize() if self.phase > Phase.DRAFT else None

    @cached_property
    def recent_history(self):
        """
        Builds a list of phases, historyitems (if one exists), and tooltip
        messages for each phase. Provides the information used in rendering the
        workflow timeline. The resulting data structure looks like:
        [
            (Phase.DRAFT, HistoryItem, "tooltip message for draft"),
            (Phase.SCREENING, None, ""),
            ...
        ]
        """

        result = []
        for phase in Phase:
            history_item = self.history.filter(prev_phase=phase).order_by("-created_at").first()
            message = ""
            if phase == Phase.CLOSED:
                if history_item and self.phase != Phase.CLOSED:
                    message = "The issue was reopened by %s on %s" % (
                        history_item.created_by,
                        dateformat(timezone.localtime(history_item.created_at), "M j, Y, g:iA"),
                    )
            elif phase == self.phase:
                message = "The issue's current phase is %s and its score is %s" % (
                    phase.name.capitalize(),
                    self.score,
                )
            elif history_item:
                if phase < self.phase:
                    message = "The %s was accepted by %s on %s" % (
                        phase.name.capitalize(),
                        history_item.created_by,
                        dateformat(timezone.localtime(history_item.created_at), "M j, Y, g:iA"),
                    )
                elif phase > self.phase:
                    message = "The %s was rejected by %s on %s" % (
                        phase.name.capitalize(),
                        history_item.created_by,
                        dateformat(timezone.localtime(history_item.created_at), "M j, Y, g:iA"),
                    )
            result.append((phase, history_item, message))
        return result

    @cached_property
    def score(self):
        """
        The all import score calculation method: calculates this issue's score
        based on its phase, time overdue, significance level, and category
        """

        # _phase is a foreign key to the ScoreCoefficient record, made available
        # in the same query via select_related
        coefficient = self._phase

        base = coefficient.base
        time = coefficient.time * max(0, (date.today() - self.due_date).days)
        significance = coefficient.significance * self.significance.weight
        category = coefficient.category * self.category.weight

        return base + time + significance + category


@receiver(post_init, sender=Issue)
@receiver(post_save, sender=Issue)
def save_initial_values(**kwargs):
    """
    Signal handler to save the initial values of fields that are relevant to the
    creation of HistoryItems for later comparison whenever a model instance is
    pulled out of the database or saved.
    """

    instance = kwargs.get("instance")
    fields = ["title", "assigned_to_id", "significance_id", "category_id", "phase", "due_date"]
    if instance.pk:
        instance.initial = {i: getattr(instance, i) for i in fields}


@receiver(pre_save, sender=Issue)
def send_email_notification(**kwargs):
    """
    Send an email to the assigned user when saving if the phase was changed.
    Does not actually send an email if DEBUG=True in settings, instead printing
    the contents of the email that would be sent to the console for inspection.
    """

    instance = kwargs.get("instance")

    # don't send email when creating an issue
    if not instance or not instance.pk:
        return

    # don't send email if phase was not changed
    if instance.phase == instance.initial["phase"]:
        return

    # don't send email when closing an issue
    if instance.phase == Phase.CLOSED:
        return

    context = {
        "user": instance.assigned_to,
        "issue": instance,
        "accepted": instance.phase > instance.initial["phase"],
    }

    contents = render_to_string("email.html", context)

    args = {
        "subject": "Issue Updated: %s" % instance.title,
        "message": contents,
        "from_email": "POTATO Notifications",
        "recipient_list": [instance.assigned_to.email],
        "html_message": contents,
    }

    if settings.DEBUG:
        print(f"---NOT ACTUALLY SENDING EMAIL---\n{args}")
    else:
        send_mail(**args)

potato/forms/baseform.py
from django.forms import ModelForm
from django.forms.widgets import DateInput, Textarea


class BaseForm(ModelForm):
    """
    Base class for other ModelForms, overrides a few default widget attributes
    throughout, for compatibility and consistency
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # remove the default trailing colon from label tags
        self.label_suffix = ""

        for name in self.fields:
            # add the form-control class to all widgets, for compatibility with bootstrap
            self.fields[name].widget.attrs["class"] = "form-control"

            if isinstance(self.fields[name].widget, DateInput):
                # add datepicker class also to date input widgets, to active datepicker js plugin
                self.fields[name].widget.attrs["class"] += " datepicker"

                # set date format for compatibility with datepicker plugin
                self.fields[name].widget.format = "%m/%d/%Y"

            if isinstance(self.fields[name].widget, Textarea):
                # reduce textarea rows from 4 to 2
                self.fields[name].widget.attrs["rows"] = 2

    class Meta:
        abstract = True

potato/forms/categoryform.py
from potato.models import Category

from .baseform import BaseForm


class CategoryForm(BaseForm):
    class Meta:
        model = Category
        fields = ["name", "weight"]

potato/views/categories.py
from django.db import IntegrityError
from django.http import HttpResponseBadRequest, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages

from potato.forms import CategoryForm
from potato.models import Category
from potato.utils import admin_only, form_errors


@admin_only
def index(request):
    """
    Display the Category Management screen
    """

    context = {
        "categories": Category.objects.order_by("weight"),
        "form": CategoryForm(prefix="add"),
    }

    return render(request, "admin/categories/index.html", context)


@admin_only
def create(request):
    """
    Accepts HTTP POST request from the Create New Category form on the Category
    Management screen to create a new Category
    """

    if request.method == "POST":
        form = CategoryForm(request.POST, prefix="add")

        if not form.is_valid():
            messages.error(request, "The following errors were detected:\n%s" % form_errors(form))
        else:
            form.save()
            messages.success(request, "New category successfully saved.")

    return redirect("admin-categories")


@admin_only
def edit(request, category_id):
    """
    Renders the contents of the Modify Category dialog, and accepts HTTP POST
    request from that dialog to modify a Category
    """

    category = get_object_or_404(Category, pk=category_id)

    if request.method == "POST":
        form = CategoryForm(request.POST, prefix="edit", instance=category)

        if not form.is_valid():
            messages.error(request, "The following errors were detected:\n%s" % form_errors(form))
        else:
            form.save()
            messages.success(request, "Category successfully edited.")

        return redirect("admin-categories")

    context = {
        "cant_delete": category.cant_delete(),
        "form": CategoryForm(prefix="edit", instance=category),
    }

    return render(request, "admin/categories/edit.html", context)


@admin_only
def delete(request, category_id):
    """
    Delete a Category by id. Checks first to see if the category can be deleted
    and returns an error message if not.
    """

    category = get_object_or_404(Category, pk=category_id)

    cant_delete = category.cant_delete()

    if cant_delete:
        messages.error(request, cant_delete)
    else:
        try:
            category.delete()
        except IntegrityError as exception:
            # IntegrityError usually means the violation of a database constraint
            messages.error(request, "Something went wrong deleting the category!")
            print(exception)
        else:
            messages.success(request, "Category successfully deleted.")

    return redirect("admin-categories")


@admin_only
def check(request, category_id=None):
    """
    Accepts HTTP GET request sent by jquery validation plugin for remote
    validation. Request contains the id of the field as the key, and the value
    entered by the user for validation as the value.
    """

    category = None
    if category_id:
        category = get_object_or_404(Category, pk=category_id)

    # validator only sends one key/value at a time for validation, so a request
    # containing more than one key is an error condition
    if len(request.GET) != 1:
        return HttpResponseBadRequest()

    form = CategoryForm(request.GET, instance=category, prefix="edit" if category_id else "add")

    # since request.GET is a QueryDict, the keys are in an arbitrary non-random
    # order and there is no way to directly "grab the first element," but we are
    # guaranteed by the above check that there is exactly one key in the dict,
    # so iterating the dict is a (roundabout) way of grabbing the element
    # without knowing the name of the key.
    for key in request.GET:
        # key will be either add-name or edit-name, depending on the form prefix
        if "name" in key:
            return JsonResponse("<br/>".join(form.errors.get("name", [])) or True, safe=False)

    return JsonResponse(False, safe=False)

potato/views/scorecoefficients.py
from django.shortcuts import redirect, render
from django.contrib import messages

from potato.forms import ScoreCoefficientForm
from potato.models import ScoreCoefficient
from potato.phase import Phase
from potato.utils import admin_only, form_errors


@admin_only
def index(request):
    """
    Display the Score Coefficient Management screen
    """

    forms = []

    # build a list of forms for each phase draft - verification, in order
    for phase in [Phase(i) for i in range(5)]:
        forms.append(
            (
                phase.name.capitalize(),
                ScoreCoefficientForm(
                    instance=ScoreCoefficient.objects.get(phase=phase), prefix=phase.name.lower()
                ),
            )
        )

    context = {"forms": forms}

    return render(request, "admin/scoring/index.html", context)


@admin_only
def edit(request):
    """
    Accepts HTTP POST request from form on Score Coefficient Management screen.
    Checks all 5 forms for errors before saving, if any have errors, none are
    saved and the error messages are returned to the user.
    """

    forms = []

    # build a list of forms for each phase draft - verification, in order
    for phase in [Phase(i) for i in range(5)]:
        forms.append(
            ScoreCoefficientForm(
                request.POST,
                instance=ScoreCoefficient.objects.get(phase=phase),
                prefix=phase.name.lower(),
            )
        )

    errors = []

    for form in forms:
        if not form.is_valid():
            errors.append(form_errors(form))

    if errors:
        messages.error(request, "The following errors were detected:\n%s" % "\n".join(errors))
    else:
        for form in forms:
            form.save()
        messages.success(request, "Score coefficients successfully saved.")

    return redirect("admin-scoring")

potato/templates/issues/list/index.html
{% extends "base.html" %}

{% block header %}{% block title %}{% if closed %}Closed{% else %}Open{% endif %} Issues{% endblock %}{% endblock %}

{% block content %}
<div id="filter-box" class="card mb-3 p-3">
    <div class="row">
        <div class="col">
            <h6 class="card-title">
                Filter Issues
            </h6>
        </div>
    </div>
    <div class="row align-items-center">
        <div class="col input-group">
            <div class="input-group-prepend">
                <div class="input-group-text">
                    <small>
                        Significance
                    </small>
                </div>
            </div>
            <select class="form-control" id="filter-significance">
                <option value="">All</option>
                {% for significance in significance_levels %}
                    <option value="{{ significance }}">{{ significance }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col input-group">
            <div class="input-group-prepend">
                <div class="input-group-text">
                    <small>
                        Category
                    </small>
                </div>
            </div>
            <select class="form-control" id="filter-category">
                <option value="">All</option>
                {% for category in categories %}
                    <option value="{{ category }}">{{ category }}</option>
                {% endfor %}
            </select>
        </div>
        {% if not closed %}
            <div class="col input-group">
                <div class="input-group-prepend">
                    <div class="input-group-text">
                        <small>
                            Username
                        </small>
                    </div>
                </div>
                <select class="form-control" id="filter-user">
                    <option value="">All</option>
                    {% for user in users %}
                        <option value="{{ user }}"
                            {% if not request.user.is_staff and request.user.pk == user.pk %}selected{% endif %}
                        >
                            {{ user }}
                        </option>
                    {% endfor %}
                </select>
            </div>
            <div class="col input-group">
                <div class="input-group-prepend">
                    <div class="input-group-text">
                        <small>
                            Phase
                        </small>
                    </div>
                </div>
                <select class="form-control" id="filter-phase">
                    <option value="">All</option>
                    <option value="Draft">Draft</option>
                    <option value="Screening">Screening</option>
                    <option value="Analysis">Analysis</option>
                    <option value="Implementation">Implementation</option>
                    <option value="Verification">Vefification</option>
                </select>
            </div>
        {% endif %}
    </div>
</div><!-- filter box -->
<div class="row mb-3">
    <div class="col">
        {% if closed %}
            <a href="{% url 'issues-open' %}" class="btn btn-secondary">
                <i class="fas fa-book-open"></i>
                View Open Issues
            </a>
        {% else %}
            <a href="{% url 'issues-closed' %}" class="btn btn-secondary">
                <i class="fas fa-book"></i>
                View Closed Issues
            </a>
        {% endif %}
    </div>
    {% if not closed %}
        <div class="col text-right">
            <a href="{% url 'issues-create' %}" class="btn btn-primary">
                <i class="fa fa-plus"></i>
                New Issue
            </a>
        </div>
    {% endif %}
</div>
<table id="issues" class="table table-striped table-hover">
    <thead>
        <tr>
            <th style="width: 10%">Issue</th>
            <th style="width: 40%">Title</th>
            <th style="width: 10%">Significance</th>
            <th style="width: 10%">Category</th>
            {% if not closed %}
            <th style="width: 10%">Username</th>
            <th style="width: 10%">Phase</th>
            <th style="width: 10%">Score</th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
        {% for issue in issues %}
            <tr data-href="{% url 'issues-edit' issue.pk %}">
                <td>{{ issue.pk }}</td>
                <td>{{ issue.title }}</td>
                <td>{{ issue.significance }}</td>
                <td>{{ issue.category }}</td>
                {% if not closed %}
                <td>{{ issue.assigned_to }}</td>
                <td>{{ issue.get__phase_display }}</td>
                <td>{{ issue.score }}</td>
                {% endif %}
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}